Support key remapping
If the 'keys' input is present and is neither true nor false, interpret
it as a list of [FOO=]BAR key-value pairs, where FOO is the name of the
envvar to set and BAR is the name of the variable to use as the value.
If FOO is omitted, BAR is also used as the name of the envvar to set. If
BAR is '*', then all unmapped variables are implicitly mapped to
themselves.

For example, the value 'GITHUB_TOKEN=PULUMI_BOT_TOKEN,AWS_KEY_ID,
AWS_SECRET_KEY,AWS_SESSION_TOKEN' will export this environment:

  GITHUB_TOKEN=PULUMI_BOT_TOKEN,
  AWS_KEY_ID=AWS_KEY_ID
  AWS_SECRET_KEY=AWS_SECRET_KEY
  AWS_SESSION_TOKEN=AWS_SESSION_TOKEN

If the source ESC env also contained other environment variables, they
would not be exported. All non-mapped variables can be exported with the
identity mapping by including '*' as a key. For example,
'GITHUB_TOKEN=PULUMI_BOT_TOKEN,*` would also export the environment
above assuming no other envvars exist in the ESC environment.

Remapping applies to action outputs as well as environment variables.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -66,6 +66,45 @@ jobs:
         env:
           K1: ${{ steps.esc.outputs.FOO }}
           K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
+  test-remap-individual-keys:
+    strategy: {matrix: {os: [ubuntu-latest]}}
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Authenticate with Pulumi Cloud
+        uses: pulumi/auth-actions@v1
+        with:
+          organization: pulumi
+          requested-token-type: urn:pulumi:token-type:access_token:organization
+          cloud-url: https://api.pulumi-staging.io
+      - name: Install ESC and open an environment
+        id: esc
+        uses: ./
+        with:
+          environment: 'pulumi/github/esc-action'
+          keys: 'BAR=FOO,SOME_IMPORTANT_KEY'
+          cloud-url: https://api.pulumi-staging.io
+          export-environment-variables: false
+      - name: Verify injection
+        run: |
+          echo "Testing env injection..."
+          REQUIRED_VARS=("K1" "K2")
+          for var in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!var}" ]]; then
+              echo "Error: $var is not set or empty" >&2
+              exit 1
+            fi
+            echo "$var is set to: ${!var}"
+          done
+          if [[ -n $(env | grep "^\(FOO\|BAR\|SOME_IMPORTANT_KEY\|TEST_ENV\)=") ]]; then
+            echo "Error: unexpected variables are set" >&2
+            env
+            exit 1
+          fi
+        env:
+          K1: ${{ steps.esc.outputs.BAR }}
+          K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
   test-all-keys:
     strategy: {matrix: {os: [ubuntu-latest]}}
     runs-on: ${{ matrix.os }}
@@ -106,6 +145,47 @@ jobs:
           K1: ${{ steps.esc.outputs.FOO }}
           K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
           K3: ${{ steps.esc.outputs.TEST_ENV }}
+  test-remap-all-keys:
+    strategy: {matrix: {os: [ubuntu-latest]}}
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Authenticate with Pulumi Cloud
+        uses: pulumi/auth-actions@v1
+        with:
+          organization: pulumi
+          requested-token-type: urn:pulumi:token-type:access_token:organization
+          cloud-url: https://api.pulumi-staging.io
+      - name: Install ESC and open an environment
+        id: esc
+        uses: ./
+        with:
+          # This action uses the https://app.pulumi-staging.io/pulumi/esc/github/esc-action environment
+          environment: 'pulumi/github/esc-action'
+          keys: 'BAR=FOO,*'
+          cloud-url: https://api.pulumi-staging.io
+          export-environment-variables: false
+      - name: Verify injection
+        run: |
+          echo "Testing env injection..."
+          REQUIRED_VARS=("K1" "K2" "K3")
+          for var in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!var}" ]]; then
+              echo "Error: $var is not set or empty" >&2
+              exit 1
+            fi
+            echo "$var is set to: ${!var}"
+          done
+          if [[ -n $(env | grep "^\(FOO\|BAR\|SOME_IMPORTANT_KEY\|TEST_ENV\)=") ]]; then
+            echo "Error: unexpected variables are set" >&2
+            env
+            exit 1
+          fi
+        env:
+          K1: ${{ steps.esc.outputs.BAR }}
+          K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
+          K3: ${{ steps.esc.outputs.TEST_ENV }}
   test-individual-key-injection:
     strategy: {matrix: {os: [ubuntu-latest]}}
     runs-on: ${{ matrix.os }}
@@ -137,6 +217,41 @@ jobs:
             echo "$var is set to: ${!var}"
           done
           if [[ -n $(env | grep "^TEST_ENV=") ]]; then
+            echo "Error: unexpected variables are set" >&2
+            env
+            exit 1
+          fi
+  test-remap-individual-key-injection:
+    strategy: {matrix: {os: [ubuntu-latest]}}
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Authenticate with Pulumi Cloud
+        uses: pulumi/auth-actions@v1
+        with:
+          organization: pulumi
+          requested-token-type: urn:pulumi:token-type:access_token:organization
+          cloud-url: https://api.pulumi-staging.io
+      - name: Inject only specific environment variables
+        id: esc
+        uses: ./
+        with:
+          environment: 'pulumi/github/esc-action'
+          keys: 'BAR=FOO,SOME_IMPORTANT_KEY'
+          cloud-url: https://api.pulumi-staging.io
+      - name: Verify injection
+        run: |
+          echo "Testing env injection..."
+          REQUIRED_VARS=("BAR" "SOME_IMPORTANT_KEY")
+          for var in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!var}" ]]; then
+              echo "Error: $var is not set or empty" >&2
+              exit 1
+            fi
+            echo "$var is set to: ${!var}"
+          done
+          if [[ -n $(env | grep "^\(TEST_ENV\|FOO\)=") ]]; then
             echo "Error: unexpected variables are set" >&2
             env
             exit 1
@@ -204,6 +319,41 @@ jobs:
             fi
             echo "$var is set to: ${!var}"
           done
+  test-remap-all-key-injection:
+    strategy: {matrix: {os: [ubuntu-latest]}}
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Authenticate with Pulumi Cloud
+        uses: pulumi/auth-actions@v1
+        with:
+          organization: pulumi
+          requested-token-type: urn:pulumi:token-type:access_token:organization
+          cloud-url: https://api.pulumi-staging.io
+      - name: Install and inject ESC environment variables
+        uses: ./
+        with:
+          # This action uses the https://app.pulumi-staging.io/pulumi/esc/github/esc-action environment
+          environment: 'pulumi/github/esc-action'
+          keys: BAR=FOO,*
+          cloud-url: https://api.pulumi-staging.io
+      - name: Verify injection
+        run: |
+          echo "Testing env injection..."
+          REQUIRED_VARS=("BAR" "SOME_IMPORTANT_KEY" "TEST_ENV")
+          for var in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!var}" ]]; then
+              echo "Error: $var is not set or empty" >&2
+              exit 1
+            fi
+            echo "$var is set to: ${!var}"
+          done
+          if [[ -n $(env | grep "^FOO=") ]]; then
+            echo "Error: unexpected variables are set" >&2
+            env
+            exit 1
+          fi
   test-oidc-config:
     strategy: {matrix: {os: [ubuntu-latest]}}
     runs-on: ${{ matrix.os }}
