Add step outputs (#12)
And allow users to avoid exporting environment variables. This allows
users to precisely control which environment variables are passed to
successive steps (analagous to the use of `secrets` with `env`).

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,85 @@ jobs:
           version: '0.10.0'
       - name: Verify CLI exists
         run: esc version
+  test-individual-keys:
+    strategy: {matrix: {os: [ubuntu-latest]}}
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Authenticate with Pulumi Cloud
+        uses: pulumi/auth-actions@v1
+        with:
+          organization: pulumi
+          requested-token-type: urn:pulumi:token-type:access_token:organization
+          cloud-url: https://api.pulumi-staging.io
+      - name: Install ESC and open an environment
+        id: esc
+        uses: ./
+        with:
+          environment: 'pulumi/github/esc-action'
+          keys: 'FOO,SOME_IMPORTANT_KEY'
+          cloud-url: https://api.pulumi-staging.io
+          export-environment-variables: false
+      - name: Verify injection
+        run: |
+          echo "Testing env injection..."
+          REQUIRED_VARS=("K1" "K2")
+          for var in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!var}" ]]; then
+              echo "Error: $var is not set or empty" >&2
+              exit 1
+            fi
+            echo "$var is set to: ${!var}"
+          done
+          if [[ -n $(env | grep "^\(FOO\|SOME_IMPORTANT_KEY\|TEST_ENV\)=") ]]; then
+            echo "Error: unexpected variables are set" >&2
+            env
+            exit 1
+          fi
+        env:
+          K1: ${{ steps.esc.outputs.FOO }}
+          K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
+  test-all-keys:
+    strategy: {matrix: {os: [ubuntu-latest]}}
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+      - name: Authenticate with Pulumi Cloud
+        uses: pulumi/auth-actions@v1
+        with:
+          organization: pulumi
+          requested-token-type: urn:pulumi:token-type:access_token:organization
+          cloud-url: https://api.pulumi-staging.io
+      - name: Install ESC and open an environment
+        id: esc
+        uses: ./
+        with:
+          # This action uses the https://app.pulumi-staging.io/pulumi/esc/github/esc-action environment
+          environment: 'pulumi/github/esc-action'
+          cloud-url: https://api.pulumi-staging.io
+          export-environment-variables: false
+      - name: Verify injection
+        run: |
+          echo "Testing env injection..."
+          REQUIRED_VARS=("K1" "K2" "K3")
+          for var in "${REQUIRED_VARS[@]}"; do
+            if [[ -z "${!var}" ]]; then
+              echo "Error: $var is not set or empty" >&2
+              exit 1
+            fi
+            echo "$var is set to: ${!var}"
+          done
+          if [[ -n $(env | grep "^\(FOO\|SOME_IMPORTANT_KEY\|TEST_ENV\)=") ]]; then
+            echo "Error: unexpected variables are set" >&2
+            env
+            exit 1
+          fi
+        env:
+          K1: ${{ steps.esc.outputs.FOO }}
+          K2: ${{ steps.esc.outputs.SOME_IMPORTANT_KEY }}
+          K3: ${{ steps.esc.outputs.TEST_ENV }}
   test-individual-key-injection:
     strategy: {matrix: {os: [ubuntu-latest]}}
     runs-on: ${{ matrix.os }}
@@ -40,6 +119,7 @@ jobs:
           requested-token-type: urn:pulumi:token-type:access_token:organization
           cloud-url: https://api.pulumi-staging.io
       - name: Inject only specific environment variables
+        id: esc
         uses: ./
         with:
           environment: 'pulumi/github/esc-action'
@@ -56,6 +136,11 @@ jobs:
             fi
             echo "$var is set to: ${!var}"
           done
+          if [[ -n $(env | grep "^TEST_ENV=") ]]; then
+            echo "Error: unexpected variables are set" >&2
+            env
+            exit 1
+          fi
   test-all-key-injection:
     strategy: {matrix: {os: [ubuntu-latest]}}
     runs-on: ${{ matrix.os }}
